default:
  server:
    port: 4843
    buildInfo:
      productName: "Dummy Dateset Server"
      buildNumber: "0001"
    ip: "0.0.0.0"
    endpointName: 'OPCUA@Siemens'
    username: 'root'
    password: 'root'
    allowAnonymous: false,
    serverInfo:
      applicationUri: "http://siemens.com/SkillOPCUA"
      productUri: "siemens.com/SP347_Example"
      applicationName: "SP347SkillEngineering@Siemens" 
    serverNodeSet: ["UA-Nodeset-master/DI/Opc.Ua.Di.PredefinedNodes.xml",
    "UA-Nodeset-master/FDI/Opc.Ua.Fdi7.PredefinedNodes.xml", 
    "UA-Nodeset-master/ISA-95/Opc.ISA95.NodeSet2.xml", 
    "UA-Nodeset-master/AML/Opc.Ua.AMLBaseTypes.NodeSet2.xml", 
    "UA-Nodeset-master/AutoID/Opc.Ua.AutoID.NodeSet2.xml",
    "UA-Nodeset-master/MachineVision/Opc.Ua.MachineVision.NodeSet2.xml"]